### ISSUE TITLE
Paging, buttons and cosmetics on list screens.

### ISSUE THREAD

**Issue by johnzastrow** [johnzastrow/choreme#12]
I think all lists should work like the parent reward screen. 

![paging2](https://user-images.githubusercontent.com/1213646/148106537-a92304ad-eaba-474b-add5-ffecdcbc0a9e.png)
![paging1](https://user-images.githubusercontent.com/1213646/148106538-7cbc7693-19b9-44bf-9a63-01265ed8b68b.png)

**Comment by lamtuanvu** [comment]
Hi John, what is the date paging in the design used for or should we remove it?

**Comment by johnzastrow** [comment]
Let's leave date paging for now. I asked to change because I couldn't see enough chores. But, The apps I've used typically use a combination of child (one or more and), and date to limit the number of chores shown. It would not be unusual to have 20 chores per child per day. It's helpful to see chores for one day. The list can be long without a filter.

**Comment by johnzastrow** [comment]
Looks good.
